sudo: false
language: c
matrix:
    fast_finish: true
os:
    - linux
    - osx
node_js:
    - 0.10
    - 0.12
    - 4
    - 5
env:
    global:
        - NODE_ENV=test
    matrix:
        - TRAVIS_NODE_VERSION="0.10"
        - TRAVIS_NODE_VERSION="0.12"
        - TRAVIS_NODE_VERSION="4"
        - TRAVIS_NODE_VERSION="5"
services:
    - couchdb
cache:
    directories:
        - node_modules
        - cozy-data-system/node_modules
        - cozy-proxy/node_modules
        - cozy-files/node_modules
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_install:
    - rm -rf ~/.nvm/
    - git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
    - source ~/.nvm/nvm.sh
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; bin/prepare_travis_for_integration_tests.sh; fi

install:
    - nvm install $TRAVIS_NODE_VERSION
    - nvm use $TRAVIS_NODE_VERSION
    - cd build/cozy-labs/cozy-desktop
    - npm install coffee-script mocha -g
    - travis_retry npm install

script:
    - bin/ci

after_failure:
    - pwd
    - $CXX --version
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
