sudo: false
language: c
matrix:
    fast_finish: true
os:
    - linux
    - osx
node_js:
    - 0.10
    - 0.12
    - 4
    - 5
env:
    global:
        - NODE_ENV=test
    matrix:
        - TRAVIS_NODE_VERSION="0.10"
        - TRAVIS_NODE_VERSION="0.12"
        - TRAVIS_NODE_VERSION="4"
        - TRAVIS_NODE_VERSION="5"
cache:
    directories:
        - node_modules
        - cozy-data-system/node_modules
        - cozy-proxy/node_modules
        - cozy-files/node_modules
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_install:
    - cd
    - mkdir -p $INDEXES_PATH
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export INDEXES_PATH=/home/travis/build/indexes; fi
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export INDEXES_PATH=/Users/travis/build/indexes; fi
    - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
    - source ~/.nvm/nvm.sh
    - nvm install 0.10
    - nvm use 0.10
    - npm install forever coffee-script -g
    - git clone --depth 1 git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - pwd
    - travis_retry npm install #data-system
    - NAME=data-system TOKEN=token forever start -o forever-ds.log -e forever-ds-err.log build/server.js
    - sleep 5
    - cd
    - git clone --depth 1 git://github.com/cozy/cozy-proxy.git
    - cd cozy-proxy
    - pwd
    - travis_retry npm install #proxy
    - NAME=proxy TOKEN=token forever start -o forever-proxy.log -e forever-proxy-err.log build/server.js
    - sleep 5
    - 'curl -X POST -H "Content-Type: application/json" -d "{ \"email\": \"cozytest@cozycloud.cc\", \"password\": \"cozytest\", \"timezone\":\"Europe/Paris\"}" http://127.0.0.1:9104/register'
    - cd
    - git clone --depth 1 git://github.com/cozy/cozy-files.git
    - cd cozy-files
    - pwd
    - travis_retry npm install #files
    - cd ~/cozy-data-system
    - coffee commands.coffee test-install files ../cozy-files/package.json
    - cd ~/cozy-files
    - NAME=files TOKEN=apptoken forever start -o forever-files.log -e forever-files-err.log build/server.js
    - sleep 3

install:
    - nvm install $TRAVIS_NODE_VERSION
    - nvm use $TRAVIS_NODE_VERSION
    - cd build/cozy-labs/cozy-desktop
    - npm install coffee-script mocha -g
    - travis_retry npm install

script:
    - bin/ci

after_failure:
    - pwd
    - $CXX --version
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
