sudo: false
language: node_js
matrix:
    fast_finish: true
node_js:
    - 0.10
    - 0.12
    - 4
    - 5
env:
    global:
        - CXX=g++-4.8
services:
    - couchdb
cache:
    directories:
        - node_modules
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

before_install:
    - cd
    - export INDEXES_PATH=/home/travis/build/indexes
    - mkdir -p $INDEXES_PATH
    - TESTED_NODE=$(node -v)
    - nvm install 0.10
    - nvm use 0.10
    - npm install forever coffee-script -g
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install #data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log -e forever-ds-err.log build/server.js
    - sleep 5
    - pwd
    - cd
    - git clone git://github.com/cozy/cozy-proxy.git
    - cd cozy-proxy
    - npm install
    - pwd
    - NAME=proxy TOKEN=token forever start -o forever-proxy.log -e forever-proxy-err.log build/server.js
    - sleep 5
    - 'curl -X POST -H "Content-Type: application/json" -d "{ \"email\": \"cozytest@cozycloud.cc\", \"password\": \"cozytest\", \"timezone\":\"Europe/Paris\"}" http://127.0.0.1:9104/register'
    - cd
    - git clone git://github.com/cozy/cozy-files.git
    - cd cozy-files
    - npm install
    - pwd
    - cd ~/cozy-data-system
    - coffee commands.coffee test-install files ../cozy-files/package.json
    - pwd
    - cd ~/cozy-files
    - NAME=files TOKEN=apptoken forever start -o forever-files.log -e forever-files-err.log build/server.js
    - sleep 3
    - nvm use $TESTED_NODE
    - cd /home/travis/build/cozy-labs/cozy-desktop
    - npm install coffee-script mocha -g
    - pwd

script:
    - bin/ci

after_failure:
    - pwd
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
