name: Setup cozy-stack
author: Erwan Guyader
description: Downloads cozy-stack, starts it and create a test instance.
runs:
  using: composite
  shell: bash
  steps:
    - name: Download cozy-stack
      run: go get github.com/cozy/cozy-stack
    - name: Create a local instance and an OAuth client
      run: |
        mkdir -p "$COZY_STACK_STORAGE"
        cozy-stack serve --fs-url "file://$COZY_STACK_STORAGE" --log-level warning >cozy-stack.log 2>&1 &
        sleep 1
        cozy-stack instances add --dev --passphrase "$COZY_PASSPHRASE" localhost:8080
        COZY_CLIENT_ID=$(cozy-stack instances client-oauth localhost:8080 http://localhost/ test github.com/cozy-labs/cozy-desktop)
        COZY_STACK_TOKEN=$(cozy-stack instances token-oauth localhost:8080 "$COZY_CLIENT_ID" io.cozy.files io.cozy.settings)
        # Variables are not directly available in next steps; we need to write them into a special file
        echo "COZY_CLIENT_ID=$COZY_CLIENT_ID" >> $GITHUB_ENV
        echo "COZY_STACK_TOKEN=$COZY_STACK_TOKEN" >> $GITHUB_ENV
    - name: Create local synchronization dir
      run: mkdir -p "$COZY_DESKTOP_DIR"
    - name: Create dummy .env.test file
      run: echo "NODE_ENV=test" > "${{ github.workspace }}/.env.test"
