name: Setup CouchDB
author: Erwan Guyader
description: Starts a CouchDB server of the given version on the given port.
inputs:
  couchdb-version:
    description: 'The version of CouchDB to run'
    required: true
  couchdb-port:
    description: 'The port on which to expose the internal CouchDB port'
    required: false
    default: 5984
runs:
  using: composite
  steps:
    - name: Setup podman-machine
      shell: bash
      run: |
        curl -L https://github.com/boot2podman/machine/releases/download/v0.17/podman-machine.darwin-amd64 --output /usr/local/bin/podman-machine
        chmod +x /usr/local/bin/podman-machine
        podman-machine create box

    - name: Setup CouchDB
      shell: bash
      run: |
        podman-machine ssh box -L ${{ inputs.couchdb-port }}:localhost:5984 -N &
        podman-machine ssh box -- sudo podman run -d -p 5984:5984 --name couch "apache/couchdb:${{ inputs.couchdb-version }}"
        curl -X PUT "http://127.0.0.1:${{ inputs.couchdb-port }}/{_users,_replicator,_global_changes}"
